---
title: "plasma_hormone_analyses_Nov13_2025"
author: "Medhavi Verma"
date: "2025-11-13"
output: pdf_document
---


Load packages 

```{r}
library(dplyr)
library(ggplot2)
library(ggbeeswarm)
library(tidyverse)
library(lme4)
library(lmerTest)
```


Read in file

```{r}
plasma_hormones <- read.csv("~/plasma_hormones.csv", header = T)
```


Plotting hormone concentrations by infection status

```{r}

cols <- c("estradiol (pg/mL)" = "#440154FF", "testosterone (ng/mL)" = "#FFB6C1")

# Converting all hormone concentrations to pg/mL
plasma_hormones <- plasma_hormones %>% 
  mutate(mean_pgml = ifelse(assay_type == "testosterone" | assay_type == "progesterone", Mean*1000, Mean))

# Males:

ggplot(plasma_hormones[plasma_hormones$Sex == "M",], aes(infection, log(mean_pgml), fill = assay_type2)) + 
  geom_boxplot(alpha = 0.3, fatten = 3, width = 0.2) + geom_beeswarm(cex = 2, size = 1) + theme_classic(base_size = 20) + labs(y = "log(Mean Plasma Concentration (pg/mL))") + facet_wrap(~assay_type, nrow = 1, scales="free_y") + geom_text(data = subset(plasma_hormones, Sex == "M" & assay_type2 == "estradiol (pg/mL)"), aes(x = "positive", y = max(log(mean_pgml), na.rm = TRUE) + 0.5, label = "**"), size = 10) + scale_x_discrete(labels=c("negative" = "non-infected", "positive" = "infected"))+ theme(legend.position = "none",axis.title.x = element_blank(), plot.title = element_text(size = 22, hjust = 0.5)) + scale_fill_manual(values = cols, aesthetics = "fill") 

# Females: 

ggplot(plasma_hormones[plasma_hormones$Sex == "F",], aes(infection, log(mean_pgml), fill = assay_type2)) + 
  geom_boxplot(alpha = 0.3, fatten = 3, width = 0.2) + geom_beeswarm(cex = 2) + 
  theme_classic(base_size = 20) + labs(y = "log(Mean Plasma Concentration (pg/mL))") + facet_wrap(~assay_type, nrow = 1) + scale_x_discrete(labels=c("negative" = "non-infected", "positive" = "infected")) + theme(legend.position = "none", axis.title.x = element_blank(), plot.title = element_text(size = 22, hjust = 0.5)) + scale_fill_manual(values = cols, aesthetics = "fill") 

```

Linear mixed-effects modeling

```{r}
# adding year column (to include as a random effect)

plasma_hormones <- plasma_hormones %>%
  mutate(
    year = ifelse(str_detect(DRT_ID, "2017"), "2017", 
                  ifelse(str_detect(DRT_ID, "2019"), "2019", 
                         ifelse(str_detect(DRT_ID, "2020"), "2020", NA)))
  )

# Subsetted data for male-testosterone

male_testosterone <- plasma_hormones %>% 
  filter(Sex == "M", assay_type == "testosterone", !(male_status == "unknown"), !(Age == "Unk"), !(is.na(Mean))) %>%
  mutate(male_status = ifelse(male_status == "natal" | male_status == "bachelor", "natal/bachelor", male_status))

# Subsetted data for male-estradiol

male_estradiol <- plasma_hormones %>% 
  filter(Sex == "M", assay_type == "estradiol", !(male_status == "unknown"), !(Age == "Unk"),!(is.na(Mean))) %>%
  mutate(male_status = ifelse(male_status == "natal" | male_status == "bachelor", "natal/bachelor", male_status))

# Subsetted data for female-testosterone

female_testosterone <- plasma_hormones %>% 
  filter(Sex == "F", assay_type == "testosterone", Age == "Adult", (repro.state.2 == "cycling"))

# Subsetted data for female-estradiol

female_estradiol <- plasma_hormones %>% 
  filter(Sex == "F", assay_type == "estradiol", Age == "Adult", (repro.state.2 == "cycling"))

# Linear mixed-effects models for males

model_males_tes <- lmer(log(Mean) ~ factor(positive) + Body_mass + Age+ factor(male_status)+ (1|year), data = male_testosterone)

summary(model_males_tes)

model_males_es <- lmer(log(Mean) ~ factor(positive) + Body_mass + Age + factor(male_status)+ (1|year), data = male_estradiol)

summary(model_males_es)

# Linear mixed-effects models for females

model_females_tes <- lmer(log(Mean) ~ factor(positive) + Body_mass+ (1|year), data = female_testosterone)

summary(model_females_tes)


model_females_es <- lmer(log(Mean) ~ factor(positive) + Body_mass+ (1|year), data = female_estradiol)

summary(model_females_es)

```

